### ISSUE TITLE
Список пользователей сервера с общей статистикой

### ISSUE THREAD

**Issue by realARCHaim** [KhaimovMR/lifds-cp#1]
http://lifeisfeudal.com/forum/posting.php?mode=quote&f=33&p=61952:

> Jintaro: Еще хорошо бы список пользователей сервера с общей статистикой типа онлайн/оффлайн, последний раз онлайн был, сколько времени был в игре суммарно, сумма скилов

**Comment by KhaimovMR** [comment]
> А это как раз к списку пользователей.
> тогда надо бы сделать разные уровни доступа, без логина пароля например только статус сервера с количеством онлайн, а с логином паролем как раз список пользователей с дополнительно кнопками бана и так далее.
> Без логина как раз можно сделать раздельчик в котором бы все кто с баном бы висели с указанием причины.
> В целом действительно бы удобно получилось
Необходимо найти в БД где хранится список банов и прочая необходимая статистика и если с этим все будет в порядке, тогда эта функция будет реализована вместе со списком пользователей.
